### ISSUE TITLE
Typo in REDAME

### ISSUE THREAD

**Issue by gianlucagiudice** [clabrugere/pytorch-scarf#1]
Hi, thank you for the great repository.

Correct me if I am wrong, but I think that here, at line 53:

https://github.com/clabrugere/pytorch-scarf/blob/067aff90164d5db96622c61b9ec741ca2d819bff/README.md?plain=1#L40-L57

you should use `ntxent_loss` instead of `criterion`

**Comment by clabrugere** [comment]
Indeed it's a mistake! Thanks for catching it creating the PR.
Cheers
